# Generated by Django 2.1 on 2018-09-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='nome',
            new_name='name',
        ),
    ]
