# Generated by Django 2.1 on 2018-10-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
                ('empenhado', models.FloatField()),
                ('anulado', models.FloatField()),
                ('liquidado', models.FloatField()),
                ('pago', models.FloatField()),
                ('data_inicio', models.DateField()),
                ('data_update', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=256)),
                ('cep', models.CharField(max_length=8)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField()),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.Instituicao')),
                ('localizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_app.Localizacao')),
            ],
        ),
        migrations.AddField(
            model_name='instituicao',
            name='localizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_app.Localizacao'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='localizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_app.Localizacao'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.Orgao'),
        ),
    ]
