# Generated by Django 2.1 on 2018-10-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_auto_20181005_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_app.Localizacao'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='telefone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='endereco',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='site',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='telefone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
