# Generated by Django 2.1 on 2018-09-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256)),
                ('valor', models.FloatField()),
                ('data_inicio', models.DateField()),
                ('prazo', models.IntegerField()),
                ('coordenadaS', models.FloatField()),
                ('coordenadaW', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, unique=True)),
                ('telefone', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('coordenadaS', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map_app.Orgao'),
        ),
    ]
