# Generated by Django 2.1 on 2018-09-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgao',
            name='coordenadaS',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='coordenadaW',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='prazo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nome',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='telefone',
            field=models.CharField(max_length=32),
        ),
    ]
