# Generated by Django 2.1 on 2018-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='coordenadaN',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
